### ISSUE TITLE
Parts of queries are incorrectly lower-cased causing errors

### ISSUE THREAD

**Issue by NoTuxNoBux** [Giorgi/GraphQLinq#15]
Hello

I have a GraphQL schema that looks somewhat like this. (I abbreviated it for brevity, but it should still be mostly complete, it was automatically generated by Keystone 6, also known as Keystone Next):

```graphql
type Query {
  sharedExperienceRooms(
    where: SharedExperienceRoomWhereInput! = {}
    orderBy: [SharedExperienceRoomOrderByInput!]! = []
    take: Int
    skip: Int! = 0
  ): [SharedExperienceRoom!]
}

type SharedExperienceRoom {
  id: ID!
  serverHost: String
}

input SharedExperienceRoomOrderByInput {
  id: OrderDirection
}

enum OrderDirection {
  asc
  desc
}

input SharedExperienceRoomWhereInput {
  id: IDFilter
}

input IDFilter {
  equals: ID
  in: [ID!]
  notIn: [ID!]
  lt: ID
  lte: ID
  gt: ID
  gte: ID
  not: IDFilter
}
```

I've then scaffolded the appropriate classes, and am the using the generated query context to do a query to fetch all items as follows:

```csharp
var query = queryContext.SharedExperienceRooms(new SharedExperienceRoomWhereInput(), new List<SharedExperienceRoomOrderByInput>(), null, 0);
```

After that, I get the following query as output from GraphQLinq:

```graphql
query (
  $where: SharedExperienceRoomWhereInput
  $orderBy: [SharedExperienceRoomOrderByInput]
  $skip: Int
) {
  result: sharedexperiencerooms(where: {}, orderBy: [], skip: 0) {
    id
  }
}
```

However, this query is not correct, as it incorrectly lower-cased `sharedExperienceRooms` to `sharedexperiencerooms`, which generates syntax errors on the side of the server.

**Comment by Giorgi** [comment]
Can you run [Introspection query](https://github.com/Giorgi/GraphQLinq/blob/master/src/GraphQLinq.Scaffolding/Program.cs#L15) against your server and attach the resulting json as a file to the issue?

**Comment by NoTuxNoBux** [comment]
Sure. The schema is slightly larger than what I posted above, though (I abbreviated it to the part that should be able to reproduce the issue):

[schema.zip](https://github.com/Giorgi/GraphQLinq/files/7176369/schema.zip)

**Comment by Giorgi** [comment]
@NoTuxNoBux This should be fixed now.
