### ISSUE TITLE
Reserved keywords are not escaped or renamed

### ISSUE THREAD

**Issue by NoTuxNoBux** [Giorgi/GraphQLinq#19]
I have a GraphQL schema from Keystone.JS 6 with the following in it:

```graphql
enum QueryMode {
  default
  insensitive
}
```

Unfortunately this results in errors after scaffolding, since `default` is reserved in C#:

```cs
namespace Foo
{
    public enum QueryMode
    {
        default,
        insensitive
    }
}
```

Reserved keywords should probably be renamed to something else or escaped somehow.

**Comment by Giorgi** [comment]
That's right, it needs to be `@default`. Can you send a PR?

**Comment by NoTuxNoBux** [comment]
Done!
